# Generated by Django 5.1.6 on 2025-04-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='student_name',
            field=models.CharField(max_length=255),
        ),
    ]
