# Generated by Django 5.1.6 on 2025-04-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_appointment_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('course_type', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
