# Generated by Django 5.1.6 on 2025-04-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
