# Generated by Django 5.1.6 on 2025-04-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_username', models.CharField(max_length=255)),
                ('teacher_name', models.CharField(max_length=255)),
                ('teacher_username', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
