# Generated by Django 5.1.6 on 2025-05-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_acceptedappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
                ('lecture_hours', models.IntegerField()),
                ('pr_hours', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
