# Generated by Django 5.1.6 on 2025-05-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course_type',
            field=models.CharField(default='Compulsary', max_length=100),
        ),
    ]
